#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=crespo
MANUFACTURER=samsung
EXT_F=EXTRACT_ROM_FILES

prop_list="system/lib/libsecril-client.so \
system/vendor/bin/gpsd \
system/vendor/bin/pvrsrvinit \
system/vendor/firmware/bcm4329.hcd \
system/vendor/firmware/cypress-touchkey.bin \
system/vendor/firmware/libpn544_fw.so \
system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
system/vendor/lib/hw/gps.s5pc110.so \
system/vendor/lib/hw/gralloc.s5pc110.so \
system/vendor/lib/libakm.so \
system/vendor/lib/libglslcompiler.so \
system/vendor/lib/libIMGegl.so \
system/vendor/lib/libpvr2d.so \
system/vendor/lib/libpvrANDROID_WSEGL.so \
system/vendor/lib/libPVRScopeServices.so \
system/vendor/lib/libsec-ril.so \
system/vendor/lib/libsrv_init.so \
system/vendor/lib/libsrv_um.so \
system/vendor/lib/libusc.so" 

prop_apk_list=""

chmod_list="gpsd \
pvrsrvinit"

pull_adb_files() {
for x in ${prop_list} ${prop_apk_list}; do
        echo "Pulling ${x} from adb connection now..."
        adb pull /${x} ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/
done

cchm=$(echo ${chmod_list} |wc -w)
if [ ${cchm} -gt 0 ]; then
for x in ${chmod_list}; do
        s=$(echo "$x" |awk -F/ '{print $NF}')
        echo "Fixing permissions for ${x} from now..."
        chmod 755 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/${s}
done
fi
}

pull_zip_files() {
if [ -d ${EXT_F} ]; then
        rm -rf ${EXT_F}
fi
unzip ${ZIP} -d ${EXT_F}

for x in ${prop_list} ${prop_apk_list}; do
        echo "Copying ${x} from ${ZIP} now..."
        cp ${EXT_F}/${x} ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/
done

cchm=$(echo ${chmod_list} |wc -w)
if [ ${cchm} -gt 0 ]; then
for x in ${chmod_list}; do
        s=$(echo "$x" |awk -F/ '{print $NF}')
        echo "Fixing permissions for ${s} from now..."
        chmod 755 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/${s}
done
fi
}

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary

if [ $# -eq  0 ]; then
        pull_adb_files
elif [ $# -eq 1 ]; then
        ZIP="${1}"
        pull_zip_files
else
        echo "Error: Too many arguments. Wanted 1 got $#"
        exit 1
fi

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# All the blobs necessary for crespo
PRODUCT_COPY_FILES += \\
EOF
chk_count=$(echo ${prop_list} |wc -w)
COUNT=0
for x in ${prop_list}; do
        COUNT=`expr ${COUNT} + 1`
        s=$(echo "$x" |awk -F/ '{print $NF}')
        if [ ${COUNT} -eq ${chk_count} ]; then
                echo "    vendor/$MANUFACTURER/$DEVICE/proprietary/${s}:${x}" >> ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
        else
                echo "    vendor/$MANUFACTURER/$DEVICE/proprietary/${s}:${x} \\" >> ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
        fi
done

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/Android.mk
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

ifeq (\$(TARGET_DEVICE),crespo)
LOCAL_PATH:=\$(call my-dir)

endif

EOF

./setup-makefiles.sh
